CREATE TABLE spotify_tracks (
    spotify_id          VARCHAR(50),
    snapshot_date       DATE,
    name                TEXT,
    artists             TEXT,
    daily_rank          INTEGER,
    daily_movement      INTEGER,
    weekly_movement     INTEGER,
    country             VARCHAR(10),
    popularity          INTEGER,
    is_explicit         BOOLEAN,
    duration_ms         INTEGER,
    album_name          TEXT,
    album_release_date  DATE,
    danceability        FLOAT,
    energy              FLOAT,
    key                 INTEGER,
    loudness            FLOAT,
    mode                INTEGER,
    speechiness         FLOAT,
    acousticness        FLOAT,
    instrumentalness    FLOAT,
    liveness            FLOAT,
    valence             FLOAT,
    tempo               FLOAT,
    time_signature      INTEGER,
    PRIMARY KEY (spotify_id, snapshot_date)
);
